# 异常处理



## Java的异常

* Java使用异常来表示错误，并通过`try ... catch`捕获异常；

  * 把可能发生异常的代码放到`try {...}`中，然后使用`catch`捕获对应的`Exception`及其子类

* Java的异常是`class`，并且从`Throwable`继承；

  

  <img src="./pics/异常的继承关系.png">

  

* `Error`是无需捕获的严重错误，`Exception`是应该捕获的可处理的错误；

* `RuntimeException`无需强制捕获，非`RuntimeException`（Checked Exception）需强制捕获，或者用`throws`声明；

* 不推荐捕获了异常但不进行任何处理。



## 捕获异常

使用`try ... catch ... finally`时：

- 多个`catch`语句的匹配顺序非常重要，子类必须放在前面；
- `finally`语句保证了有无异常都会执行，它是可选的；
- 一个`catch`语句也可以匹配多个非继承关系的异常。



## 抛出异常

* 如何抛出异常

  1. 创建某个`Exception`的实例；

  2. 用`throw`语句抛出。

     ```java
     // 抛出异常
     void process2(String s) {
         if (s == null) {
             // 抛出异常
             NullPointerException e = new NullPointerException();
             throw e;
             // 抛出异常的代码一般都合写成一行，如下
             throw new NullPointerException();
         }
     }
     ```

     

* 调用`printStackTrace()`可以打印异常的传播栈，对于调试非常有用；

  * 有了完整的异常栈的信息，我们才能快速定位并修复代码的问题。

* 捕获异常并再次抛出新的异常时，应该持有原始异常信息；

* 通常不要在`finally`中抛出异常。

  * 此情况中，`finally`抛出异常后，原来在`catch`中准备抛出的异常就“消失”了，因为只能抛出一个异常。没有被抛出的异常称为“被屏蔽”的异常（Suppressed Exception）。
  * 如果在`finally`中抛出异常，应该将原始异常加入到原有异常中。调用方可通过`Throwable.getSuppressed()`获取所有添加的`Suppressed Exception`。